name: kliniku
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # iOS Icons
  cupertino_icons: ^1.0.2
  # One Time Onboarding
  shared_preferences: ^2.0.13
  # Curved Navigation
  curved_navigation_bar: ^1.0.3
  # Firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_messaging: ^11.4.2
  flutter_local_notifications: ^9.6.1
  firebase_analytics: ^9.1.10
  http: ^0.13.4
  # Map
  flutter_map: ^1.1.0
  latlong: ^0.6.1
  url_launcher: ^6.1.3
  # Icon App
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # Arimo
    - family: Arimo
      fonts:
        - asset: fonts/Arimo-Regular.ttf
        - asset: fonts/Arimo-Bold.ttf
          weight: 700
    # Montserrat
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    #  Nunito
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
    # Roboto
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  image_path: 'assets/icons/kliniku-logo.png'
  android: true
